SELECT *
FROM customer_n
LIMIT 12;

--Q1. What is the total revenue generated by male vs. female customers?

SELECT gender,SUM(purchase_amount)
FROM customer_n
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

WITH average_purchase_amount as 
	(
	SELECT AVG(purchase_amount) as average_amount
	from customer_n
	)
SELECT customer_id
FROM customer_n
WHERE discount_applied='Yes' AND purchase_amount>(SELECT average_amount FROM average_purchase_amount);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased,ROUND(AVG(review_rating),2) as average_review
FROM customer_n
GROUP BY item_purchased
ORDER BY average_review DESC
LIMIT  5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT shipping_type,ROUND(AVG(purchase_amount),2) as average_purchase
FROM customer_n
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT 
	subscription_status,
	ROUND(AVG(purchase_amount),2) as average_purchase,
	ROUND(SUM(purchase_amount),2) as total_revenue,
	COUNT(subscription_status) as total_purchases
FROM customer_n
GROUP BY subscription_status;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,ROUND(100.0*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as perc_purchases
FROM customer_n
GROUP BY item_purchased
ORDER BY perc_purchases desc
LIMIT  5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH segmented_customers as (
	SELECT customer_id,previous_purchases,
		CASE 
			WHEN previous_purchases=1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
		END AS segments
	FROM customer_n

	)

SELECT segments, COUNT(customer_id)as count_of_people
FROM segmented_customers
GROUP BY segments;

--Q8. What are the top 3 most purchased products within each category? 

WITH ranks as (
	SELECT category,item_purchased,COUNT(customer_id)as total_orders ,RANK() OVER(PARTITION BY category order by COUNT(customer_id) desc) as r
	FROM customer_n
	GROUP BY category,item_purchased)

SELECT category,item_purchased,total_orders
FROM ranks 
WHERE r<=3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT ROUND(100*SUM(CASE WHEN subscription_status='Yes' then 1 else 0 END)/count(*),2) as perc_subscribed
FROM customer_n
WHERE previous_purchases>5;

--Q10. What is the revenue contribution of each age group? 

SELECT age_group,SUM(purchase_amount) as t_revenue,ROUND(100*SUM(purchase_amount)/(SELECT SUM(purchase_amount) FROM customer_n),2) as perc_revenue
FROM customer_n
GROUP BY age_group
order by percentage_revenue DESC;

-- Q11. Rank customers by purchase amount within each age group

WITH ranks as (
	SELECT customer_id,age_group,purchase_amount,RANK() OVER(PARTITION BY age_group ORDER BY purchase_amount DESC) AS r
	FROM customer_n
	)
SELECT age_group,customer_id,purchase_amount
FROM ranks
WHERE r <6

-- Q12. Churn Risk Analysis — Subscribers with low ratings and infrequent purchases
-- (Shows business logic + CASE)
SELECT 
    customer_id,
    age_group,
    review_rating,
    frequency_of_purchases,
    previous_purchases,
    CASE 
        WHEN review_rating < 3.0 
         AND frequency_of_purchases IN ('Annually', 'Quarterly') 
        THEN 'High Churn Risk'
        WHEN review_rating BETWEEN 3.0 AND 3.5 
         AND frequency_of_purchases = 'Quarterly'
        THEN 'Medium Churn Risk'
        ELSE 'Low Churn Risk'
    END AS churn_risk
FROM customer_n
WHERE subscription_status = 'Yes'
ORDER BY review_rating ASC;